server {
    host = 127.0.0.1
    host = ${?HTTP_HOST}
    port = 8080
    port = ${?HTTP_PORT}
}
limits {
    requestBodyLimit = ${?REQ_BODY_LIMIT}
}

db {
    jdbcUrl = "jdbc:sqlite:${user.dir}/data/data.db"
    jdbcUrl = ${?DB_URL}
    user = ${?DB_USER}
    password = ${?DB_PASS}
    databaseName = ${?DB_DBNAME}
    portNumber = ${?DB_PORT}
}

repo {
    readOnlyMode = false
    readOnlyMode = ${?REPO_READONLY_MODE}

    objectCachePolicy.maxSize = 1024
    configCachePolicy.maxSize = 1024
}