package com.moshy.drugcalc.util

import org.slf4j.Logger
import org.slf4j.Marker

class ContextNameLogger(private val logger: Logger, private val contextName: String): Logger by logger {
    override fun getName(): String = logger.name + "[$contextName]"
    
    /* TODO: this should be autogenerated from a pattern */

    /* slf4j.Logger.trace */
    override fun trace(msg: String?) = doTrace(null, msg)
    override fun trace(format: String?, arg1: Any?) = doTrace(null, format, arg1)
    override fun trace(msg: String?, t: Throwable?) = doTrace(null, msg, t)
    override fun trace(format: String?, arg1: Any?, arg2: Any?) = doTrace(null, format, arg1, arg2)
    override fun trace(format: String?, vararg args: Any?) = doTrace(null, format, *args)
    override fun trace(marker: Marker?, msg: String?) = doTrace(marker, msg)
    override fun trace(marker: Marker?, format: String?, arg: Any?) = doTrace(marker, format, arg)
    override fun trace(marker: Marker?, format: String?, arg1: Any?, arg2: Any?) = doTrace(marker, format, arg1, arg2)
    override fun trace(marker: Marker?, msg: String?, t: Throwable?) = doTrace(marker, msg, t)
    override fun trace(marker: Marker?, format: String?, vararg p2: Any?) = doTrace(marker, format, *p2)
    private fun doTrace(marker: Marker?, format: String?, vararg p2: Any?) =
        logger.trace(marker, "{}: $format", contextName, *p2)

    /* slf4j.Logger.debug */
    override fun debug(msg: String?) = doDebug(null, msg)
    override fun debug(format: String?, arg1: Any?) = doDebug(null, format, arg1)
    override fun debug(msg: String?, t: Throwable?) = doDebug(null, msg, t)
    override fun debug(format: String?, arg1: Any?, arg2: Any?) = doDebug(null, format, arg1, arg2)
    override fun debug(format: String?, vararg args: Any?) = doDebug(null, format, *args)
    override fun debug(marker: Marker?, msg: String?) = doDebug(marker, msg)
    override fun debug(marker: Marker?, format: String?, arg: Any?) = doDebug(marker, format, arg)
    override fun debug(marker: Marker?, format: String?, arg1: Any?, arg2: Any?) = doDebug(marker, format, arg1, arg2)
    override fun debug(marker: Marker?, msg: String?, t: Throwable?) = doDebug(marker, msg, t)
    override fun debug(marker: Marker?, format: String?, vararg p2: Any?) = doDebug(marker, format, *p2)
    private fun doDebug(marker: Marker?, format: String?, vararg p2: Any?) =
        logger.debug(marker, "{}: $format", contextName, *p2)

    /* slf4j.Logger.info */
    override fun info(msg: String?) = doInfo(null, msg)
    override fun info(format: String?, arg1: Any?) = doInfo(null, format, arg1)
    override fun info(msg: String?, t: Throwable?) = doInfo(null, msg, t)
    override fun info(format: String?, arg1: Any?, arg2: Any?) = doInfo(null, format, arg1, arg2)
    override fun info(format: String?, vararg args: Any?) = doInfo(null, format, *args)
    override fun info(marker: Marker?, msg: String?) = doInfo(marker, msg)
    override fun info(marker: Marker?, format: String?, arg: Any?) = doInfo(marker, format, arg)
    override fun info(marker: Marker?, format: String?, arg1: Any?, arg2: Any?) = doInfo(marker, format, arg1, arg2)
    override fun info(marker: Marker?, msg: String?, t: Throwable?) = doInfo(marker, msg, t)
    override fun info(marker: Marker?, format: String?, vararg p2: Any?) = doInfo(marker, format, *p2)
    private fun doInfo(marker: Marker?, format: String?, vararg p2: Any?) =
        logger.info(marker, "{}: $format", contextName, *p2)

    /* slf4j.Logger.warn */
    override fun warn(msg: String?) = doWarn(null, msg)
    override fun warn(format: String?, arg1: Any?) = doWarn(null, format, arg1)
    override fun warn(msg: String?, t: Throwable?) = doWarn(null, msg, t)
    override fun warn(format: String?, arg1: Any?, arg2: Any?) = doWarn(null, format, arg1, arg2)
    override fun warn(format: String?, vararg args: Any?) = doWarn(null, format, *args)
    override fun warn(marker: Marker?, msg: String?) = doWarn(marker, msg)
    override fun warn(marker: Marker?, format: String?, arg: Any?) = doWarn(marker, format, arg)
    override fun warn(marker: Marker?, format: String?, arg1: Any?, arg2: Any?) = doWarn(marker, format, arg1, arg2)
    override fun warn(marker: Marker?, msg: String?, t: Throwable?) = doWarn(marker, msg, t)
    override fun warn(marker: Marker?, format: String?, vararg p2: Any?) = doWarn(marker, format, *p2)
    private fun doWarn(marker: Marker?, format: String?, vararg p2: Any?) =
        logger.warn(marker, "{}: $format", contextName, *p2)

    /* slf4j.Logger.error */
    override fun error(msg: String?) = doError(null, msg)
    override fun error(format: String?, arg1: Any?) = doError(null, format, arg1)
    override fun error(msg: String?, t: Throwable?) = doError(null, msg, t)
    override fun error(format: String?, arg1: Any?, arg2: Any?) = doError(null, format, arg1, arg2)
    override fun error(format: String?, vararg args: Any?) = doError(null, format, *args)
    override fun error(marker: Marker?, msg: String?) = doError(marker, msg)
    override fun error(marker: Marker?, format: String?, arg: Any?) = doError(marker, format, arg)
    override fun error(marker: Marker?, format: String?, arg1: Any?, arg2: Any?) = doError(marker, format, arg1, arg2)
    override fun error(marker: Marker?, msg: String?, t: Throwable?) = doError(marker, msg, t)
    override fun error(marker: Marker?, format: String?, vararg p2: Any?) = doError(marker, format, *p2)
    private fun doError(marker: Marker?, format: String?, vararg p2: Any?) =
        logger.error(marker, "{}: $format", contextName, *p2)
}